### PR TITLE
feat(#220):

### PR DESCRIPTION
**Pull request by Helltab**
#220 
#222 
1. Feature about embedding grafana-url into metrics page of /resources/application
2. Add a fresh button to reload iframe， and add a grafana-button to open a new page for grafana
3. Modify the Website Title
4. Add footer

### CODE REVIEW

**Review by jianyi-gronk — APPROVED** [review]
LGTM.

**Review by ikun-Lg — COMMENTED** [review]
LGTM.👍

**Review by ikun-Lg — APPROVED** [review]
LGTM.👍

**Comment by SDUWYS** [comment]
LGTM.

**Pull request merged**
